server:
  port: 9088
netty:
  port: 10888
  max-frame-len: 65535
  max-threads: 1024
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://47.92.204.214:5602;database=DORUN_LIFE;integratedSecurity=false
    username: sa
    password: Dorun123456
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runsMillis: 60000
      min-evictable-idle-timeMillis: 300000
      validation-query: select 'x' FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      use-global-data-source-stat: true
pay-file:
  save-path: D:\alipay\upload
logging:
  path: D:\RunAlipayPlus\log
  level:
    org.springframework.web: DEBUG
    com.run.core.alipay: DEBUG